CrudNetMVC/CrudNetMVC/Models/Contacto.cs
using System.ComponentModel.DataAnnotations;

namespace CrudNetMVC.Models
{
    public class Contacto
    {   
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "El campo Nombre es obligatorio")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "El campo Telefono es obligatorio")]
        public string Telefono { get; set; }
        [Required(ErrorMessage = "El campo Celular es obligatorio")]
        public string Celular { get; set; }
        [Required(ErrorMessage = "El campo Correo es obligatorio")]
        [EmailAddress(ErrorMessage = "El campo Correo no es un correo valido")]
        public string Correo { get; set; }
        public DateTime FechaCreacion { get; set; }

    }
}

CrudNetMVC/CrudNetMVC/Models/ErrorViewModel.cs
namespace CrudNetMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CrudNetMVC/CrudNetMVC/Controllers/InicioController.cs
using System.Diagnostics;
using CrudNetMVC.Datos;
using CrudNetMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CrudNetMVC.Controllers
{
    public class InicioController : Controller
    {
        private readonly ApplicationDbContext _context; 

        public InicioController(ApplicationDbContext contexto)
        {
            _context = contexto;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Contacto.ToListAsync());
        }

        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Crear(Contacto contacto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contacto);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(contacto);
        }

        [HttpGet]
        public async Task<IActionResult> Editar(int? id)
        {
            var contacto = await _context.Contacto.FindAsync(id);
            if (contacto == null)
            {
                return NotFound();
            }
            return View(contacto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(Contacto contacto)
        {
            if (ModelState.IsValid)
            {
                _context.Contacto.Update(contacto);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(contacto);
        }

        [HttpGet]
        public async Task<IActionResult> Detalles(int? id)
        {
            var contacto = await _context.Contacto.FindAsync(id);
            if (contacto == null)
            {
                return NotFound();
            }
            return View(contacto);
        }

        [HttpGet]
        public async Task<IActionResult> Borrar(int? id)
        {
            var contacto = await _context.Contacto.FindAsync(id);
            if (contacto == null)
            {
                return NotFound();
            }
            return View(contacto);
        }

        [HttpPost, ActionName("Borrar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BorrarContacto(int? id)
        {
            var contacto = await _context.Contacto.FindAsync(id);
            if (contacto != null)
            {
                _context.Contacto.Remove(contacto);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CrudNetMVC/CrudNetMVC/Views/Inicio/Borrar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model CrudNetMVC.Models.Contacto
@{
    ViewData["Title"] = "Borrar Contacto";
}

<h1 class="text-center">Contacto con .NET7 (.NET core MVC)</h1>

<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white"><strong>Borrar Usuario Contacto</strong></h3>
            </div>
            
            <div class="card-body">
                <form asp-action="Borrar" method="post">
                @*ID del usuario como campo oculto*@
                <input type="hidden" asp-for="Id" />
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <ul class="list-group">
                    <li class="list-group-item"><strong>Nombre: </strong>@Html.DisplayFor(m => m.Nombre)</li>
                    <li class="list-group-item"><strong>Telefono: </strong>@Html.DisplayFor(m => m.Telefono)</li>
                    <li class="list-group-item"><strong>Celular: </strong>@Html.DisplayFor(m => m.Celular)</li>
                    <li class="list-group-item"><strong>Correo: </strong>@Html.DisplayFor(m => m.Correo)</li>
                </ul>
                <div class="form-group text-center mt-3">
                    <button type="submit" class="btn btn-danger"><i class="bi bi-person-fill"></i> Borrar Contacto</button>
                </div>
                </form>
                <a asp-action="Index" asp-action="Index" class="btn btn-primary btn-sm mt-3">Volver</a>
            </div>
        </div>
    </div>
</div>

CrudNetMVC/CrudNetMVC/Views/Inicio/Crear.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model CrudNetMVC.Models.Contacto
@{
    ViewData["Title"] = "Crear Nuevo Contacto";
}

<h1 class="text-center">Contacto con .NET7 (.NET core MVC)</h1>

<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white"><strong>Crear Usuario Contacto</strong></h3>
            </div>

            <div class="card-body">
                <form asp-action="Crear" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Nombre" class="control-label"></label>
                        <input asp-for="Nombre" class="form-control" placeholder="Ingresa el Nombre" />
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Telefono" class="control-label"></label>
                        <input asp-for="Telefono" class="form-control" placeholder="Ingresa el Telefono" />
                        <span asp-validation-for="Telefono" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Celular" class="control-label"></label>
                        <input asp-for="Celular" class="form-control" placeholder="Ingresa el Celular" />
                        <span asp-validation-for="Celular" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Correo" class="control-label"></label>
                        <input asp-for="Correo" class="form-control" placeholder="Ingresa el Correo" />
                        <span asp-validation-for="Correo" class="text-danger"></span>
                    </div>

                    <div class="form-group text-center mt-3">
                        <button type="submit" class="btn btn-secondary"><i class="bi bi-person-fill"></i> Crear Contacto</button>
                    </div>
                </form>
                <a asp-action="Index" asp-action="Index" class="btn btn-primary btn-sm">Volver</a> 
            </div>
        </div>
    </div>
</div>

CrudNetMVC/CrudNetMVC/Views/Inicio/Detalles.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


@model CrudNetMVC.Models.Contacto
@{
    ViewData["Title"] = "Detalles Contacto";
}

<h1 class="text-center">Contacto con .NET7 (.NET core MVC)</h1>

<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white"><strong>Editar Usuario Contacto</strong></h3>
            </div>

            <div class="card-body">
                <ul class="list-group">
                    <li class="list-group-item"><strong>Nombre: </strong>@Html.DisplayFor(m => m.Nombre)</li>
                    <li class="list-group-item"><strong>Telefono: </strong>@Html.DisplayFor(m => m.Telefono)</li>
                    <li class="list-group-item"><strong>Celular: </strong>@Html.DisplayFor(m => m.Celular)</li>
                    <li class="list-group-item"><strong>Correo: </strong>@Html.DisplayFor(m => m.Correo)</li>
                </ul>
                <a asp-action="Index" asp-action="Index" class="btn btn-primary btn-sm mt-3">Volver</a>
            </div>
        </div>
    </div>
</div>

CrudNetMVC/CrudNetMVC/Views/Inicio/Editar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model CrudNetMVC.Models.Contacto
@{
    ViewData["Title"] = "Editar Contacto";
}

<h1 class="text-center">Contacto con .NET7 (.NET core MVC)</h1>

<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white"><strong>Editar Usuario Contacto</strong></h3>
            </div>

            <div class="card-body">
                <form asp-action="Editar">

                    <!--ID del usuario como campo oculto-->
                    <input type="hidden" asp-for="Id" />
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Nombre" class="control-label"></label>
                        <input asp-for="Nombre" class="form-control" placeholder="Ingresa el Nombre" />
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Telefono" class="control-label"></label>
                        <input asp-for="Telefono" class="form-control" placeholder="Ingresa el Telefono" />
                        <span asp-validation-for="Telefono" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Celular" class="control-label"></label>
                        <input asp-for="Celular" class="form-control" placeholder="Ingresa el Celular" />
                        <span asp-validation-for="Celular" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Correo" class="control-label"></label>
                        <input asp-for="Correo" class="form-control" placeholder="Ingresa el Correo" />
                        <span asp-validation-for="Correo" class="text-danger"></span>
                    </div>

                    <div class="form-group text-center mt-3">
                        <button type="submit" class="btn btn-primary"><i class="bi bi-pencil-fill"></i> Editar Contacto</button>
                    </div>
                </form>
                <a asp-action="Index" asp-action="Index" class="btn btn-primary btn-sm">Volver</a>
            </div>
        </div>
    </div>
</div>

CrudNetMVC/CrudNetMVC/Views/Inicio/Index.cshtml
@model IEnumerable<CrudNetMVC.Models.Contacto>
@{
    ViewData["Title"] = "Lista de contacto";
}

<h1 class="text-center my-4">Contacto con .NET7 (.NET Core MVC)</h1>

<div class="row mb-4">
    <div class="col-12 text-end">
        <a asp-action="Crear" asp-controller="Inicio" class="btn btn-primary btn-lg">
            <i class="bi bi-file-plus-fill"></i> Nuevo Usuario
        </a>
    </div>
</div>

<div class="row justify-content-center">
    <div class="col-md-10">
        <div class="card shadow-sm">
            <div class="card-header bg-dark text-white">
                <h4 class="mb-0"><i class="bi bi-list-ul"></i> Lista de Usuarios</h4>
            </div>

            <div class="card-body bg-light">
                <div class="table-responsive">
                    @if (Model.Any())
                    {
                        <table class="table table-bordered table-striped align-middle" id="tbUsuarios" cellspacing="0">
                            <thead class="table-dark text-center">
                                <tr>
                                    <th>@Html.DisplayNameFor(m => m.Id)</th>
                                    <th>@Html.DisplayNameFor(m => m.Nombre)</th>
                                    <th>@Html.DisplayNameFor(m => m.Telefono)</th>
                                    <th>@Html.DisplayNameFor(m => m.Celular)</th>
                                    <th>@Html.DisplayNameFor(m => m.Correo)</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(mbox => item.Id)</td>
                                        <td>@Html.DisplayFor(mbox => item.Nombre)</td>
                                        <td>@Html.DisplayFor(mbox => item.Telefono)</td>
                                        <td>@Html.DisplayFor(mbox => item.Celular)</td>
                                        <td>@Html.DisplayFor(mbox => item.Correo)</td>
                                        <td class="text-center">
                                            <a class="btn btn-warning btn-sm me-1" asp-action="Editar" asp-route-id="@item.Id"><i class="bi bi-pencil-fill"></i>Editar</a>
                                            <a class="btn btn-info btn-sm me-1" asp-action="Detalles" asp-route-id="@item.Id"><i class="bi bi-info-circle-fill"></i>Detalles</a>
                                            <a class="btn btn-danger btn-sm" asp-action="Borrar" asp-route-id="@item.Id"><i class="bi bi-eraser-fill"></i>Eliminar</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                    else
                    {
                        <div class="alert alert-warning text-center">
                            No hay registros disponibles.
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#tbUsuarios').DataTable({
                language: {
                    "decimal": "",
                    "emptyTable": "No hay información",
                    "info": "Mostrando _START_ a _END_ de _TOTAL_ entradas",
                    "infoEmpty": "Mostrando 0 a 0 de 0 entradas",
                    "infoFiltered": "(filtrado de _MAX_ entradas totales)",
                    "lengthMenu": "Mostrar _MENU_ entradas",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "zeroRecords": "Sin resultados encontrados",
                    "paginate": {
                        "first": "Primero",
                        "last": "Último",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    }
                }
            });
        });
    </script>
}

CrudNetMVC/CrudNetMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrudNetMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CrudNetMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">CrudNetMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Inicio" asp-action="Index">Inicio</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - CrudNetMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>